name: ZAP-Hosting ESX Pack
version: v1.0
author: ZAP-Hosting.com & the ESX Team
description: An ESX pack with additional bug-fixes, based on esx-legacy.

variables:
  steam_webApiKey: "none"

tasks:
  # Download default CFX resources
  - action: download_github
    src: https://github.com/citizenfx/cfx-server-data
    ref: 0169fdddaa9511558cfa17bcf80a832f56c359ff
    subpath: resources
    dest: ./resources

  - action: download_github
    src: https://github.com/zap-fivem/esx_12_recipe 
    dest: ./tmp/zap_esx
    
  - action: download_github
    src: https://github.com/zap-fivem/esx_12
    dest: ./resources/[esx]

  - action: move_path
    src: ./tmp/zap_esx/server.cfg
    dest: ./server.cfg

  - action: move_path
    src: ./tmp/zap_esx/zap96x96.png
    dest: ./zap96x96.png

  - action: connect_database
  - action: query_database
    file: ./resources/[esx]/esx_final.sql

  # other required resources
  - action: download_github
    src: https://github.com/Blumlaut/EasyAdmin
    ref: 36379b4eb729cb67c0c0532f20e04f6fb1c2b378
    dest: ./resources/EasyAdmin

  - action: download_github
    src: https://github.com/brouznouf/fivem-mysql-async
    ref: c5fa317a65acfe2eef453257e19e3b4fde137089
    dest: ./resources/mysql-async

  - action: download_github
    src: https://github.com/Bob74/bob74_ipl
    ref: master
    dest: ./resources/bob74_ipl
    
  - action: remove_path
    path: ./tmp
